#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-snappy
Version  : 0.4
Release  : 3
URL      : https://repo1.maven.org/maven2/org/iq80/snappy/snappy/0.4/snappy-0.4.jar
Source0  : https://repo1.maven.org/maven2/org/iq80/snappy/snappy/0.4/snappy-0.4.jar
Source1  : https://repo1.maven.org/maven2/org/iq80/snappy/snappy/0.2/snappy-0.2.jar
Source2  : https://repo1.maven.org/maven2/org/iq80/snappy/snappy/0.2/snappy-0.2.pom
Source3  : https://repo1.maven.org/maven2/org/iq80/snappy/snappy/0.4/snappy-0.4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-snappy-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-snappy package.
Group: Data

%description data
data components for the mvn-snappy package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/iq80/snappy/snappy/0.4
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/iq80/snappy/snappy/0.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/iq80/snappy/snappy/0.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/iq80/snappy/snappy/0.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/iq80/snappy/snappy/0.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/iq80/snappy/snappy/0.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/iq80/snappy/snappy/0.4
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/iq80/snappy/snappy/0.4


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/iq80/snappy/snappy/0.2/snappy-0.2.jar
/usr/share/java/.m2/repository/org/iq80/snappy/snappy/0.2/snappy-0.2.pom
/usr/share/java/.m2/repository/org/iq80/snappy/snappy/0.4/snappy-0.4.jar
/usr/share/java/.m2/repository/org/iq80/snappy/snappy/0.4/snappy-0.4.pom
